default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: Gg186988&
  port: 5433

development:
  <<: *default
  database: my_budget_app_development
  host: localhost
  username: postgres
  password: Gg186988&
  port: 5433

test:
  <<: *default
  database: my_budget_app_test
  host: localhost
  username: postgres
  password: Gg186988&
  port: 5433

production:
  <<: *default
  database: my_budget_app_production
  username: my_budget_app
  password: <%= ENV["YOURAPPNAME_DATABASE_PASSWORD"] %>
